# Generated by Django 3.1.7 on 2021-02-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
