# Generated by Django 3.1.7 on 2021-02-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210225_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name_plural': 'news'},
        ),
    ]
